#!/bin/sh

DAEMON_NAME="namios-compositor"
DAEMON_PATH="/usr/bin/namios-compositor"
PIDFILE="/var/run/${DAEMON_NAME}.pid"

case "$1" in
    start)
        echo "Starting $DAEMON_NAME..."
        if [ -f $PIDFILE ]; then
            echo "$DAEMON_NAME is already running."
        else
            # Запускаем композитор
            $DAEMON_PATH &
            echo $! > $PIDFILE
            echo "$DAEMON_NAME started."
        fi
        ;;
    stop)
        echo "Stopping $DAEMON_NAME..."
        if [ -f $PIDFILE ]; then
            kill $(cat $PIDFILE)
            rm -f $PIDFILE
            echo "$DAEMON_NAME stopped."
        else
            echo "$DAEMON_NAME is not running."
        fi
        ;;
    restart)
        $0 stop
        sleep 2
        $0 start
        ;;
    status)
        if [ -f $PIDFILE ]; then
            echo "$DAEMON_NAME is running (PID: $(cat $PIDFILE))"
        else
            echo "$DAEMON_NAME is not running."
        fi
        ;;
    *)
        echo "Usage: $0 {start|stop|restart|status}"
        exit 1
        ;;
esac

exit 0